# Generated by Django 5.0 on 2024-01-02 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybookstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
    ]
